### ISSUE TITLE
i wish i didnt have to use rocket-loader.min.js to load the links

### ISSUE THREAD

**Issue by JasonTable** [PaperMC/papermc.io#129]
i dont trust cloudflare so i block the /cdn-cgi/ url with ublock. however this seems to break the listing of the papermc builds. i know this issue will be closed as wont-fix because its my problem brought on by myself. but i just wanted to complain lol. i do like papermc though. used to use it before i started blocking that url.

i dont care if this doesn't get fixed. i will develop my own work around using the API. which could be used to make a *gasp* auto updater. however i will not do that.

**Comment by Proximyst** [comment]
This is indeed being closed as won't fix. We use Cloudflare to cache data, as the bandwidth just the last two days is up at several terabytes. This is not sustainable for us to handle on our own server. I apologise that it doesn't work as you'd like it to, and I absolutely applaud you if you want to make a CLI tool or something else to fetch builds in the same fashion through the API we provide.

Feel free to drop by in the Discord if you'd like to discuss such a tool. It could very much be useful 😃.

**Comment by MiniDigger** [comment]
rocket loader is used to defer loading of JS to noticeably speed up the website. sure, on the download page in particular it doesnt make much sense, but other pages it creates a noticeably better user experience, especially on the forums.
