### ISSUE TITLE
Wrong link on the Website

### ISSUE THREAD

**Issue by antonstech** [PaperMC/papermc.io#137]
When you click on the blue #7076 here:
![image](https://user-images.githubusercontent.com/58666027/145598411-72117c98-7d63-4f69-a781-4caab72f2782.png)
You are getting redirected to https://github.com/PaperMC/Paper/issues/7076 which throws a 404
The correct link is https://github.com/PaperMC/Paper/pull/7076 because it is a Pull Request
Greetings, Anton

**Comment by Machine-Maker** [comment]
Yeah, at some point recently, GitHub decided to remove automatic redirects. Since you cant have an issue and pull request with the same number, it used to auto redirect to the correct url. But not anymore.

**Comment by sulu5890** [comment]
GitHub has reverted this change.
