### ISSUE TITLE
"Uncaught exception in thread Profile Lookup Executor" error spam

### ISSUE THREAD

**Issue by protected22** [PaperMC/papermc.io#162]
I keep getting the "Uncaught exception in thread Profile Lookup Executor" error spam. Even after updating GeyserMC and Floodgate (which they said should've fixed it). 

https://pastebin.com/SDg3qZ2S 

When checking version:
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

Geyser dump file: (since some people claim it's because of them)
https://dump.geysermc.org/nFlQt4TjxRxcuLYTpBFjkbu57a5q5xiX

**Comment by electronicboy** [comment]
bad skulls created when using floodgate for that version will be borked, there is no trivial way to find out where they are but, fixing the issue causing bad data doesn't fix the bad data.

This is also not the place for support.
