### ISSUE TITLE
Version not found

### ISSUE THREAD

**Issue by UndercoverNL** [PaperMC/papermc.io#167]
So I am trying to use the papermc API to grab all the available versions and builds, however, not all versions shown on https://papermc.io/api/v2/projects/paper are available when trying https://papermc.io/api/v2/projects/paper/versions/1.8 to get the available builds for those versions, it starts from https://papermc.io/api/v2/projects/paper/versions/1.12 while the versions list shows from 1.8

Is this ment? Since currently, I can't make my system functional because I do list 1.8 because its in the versions list, but I can't get the builds for it.

**Comment by electronicboy** [comment]
1.8 is not in the versions list, its defined as a version group but there is no actual published jars for 1.8 itself

**Comment by UndercoverNL** [comment]
> 1.8 is not in the versions list, its defined as a version group but there is no actual published jars for 1.8 itself

why isn't it removed from the version group then?

**Comment by electronicboy** [comment]
jars are published for 1.8.8, 1.8.8 is a member of the 1.8 version group
