### ISSUE TITLE
repeating_command_block are sometimes not working when server started 1.14.x

### ISSUE THREAD

**Issue by willis1030** [PaperMC/papermc.io#22]
repeating_command_block are sometimes not working when server started 1.14.x.
I must go creative mode and re-open the repeating_command_block to make it work.
please fix it thank you.

**Comment by MiniDigger** [comment]
please open an issue in the correct repo: 
https://github.com/PaperMC/Paper/issues/new/choose

please also provide more details to what exactly you are doing.
