### ISSUE TITLE
Links to 1.14.4 downloads are broken

### ISSUE THREAD

**Issue by eccentricdevotion** [PaperMC/papermc.io#26]
`{"error":{"code":404,"message":"Could not locate build"}}`
Download URLs have the incorrect version string in them
Current URL: https://papermc.io/api/v1/paper/**1.14.3**/137/download
Should be: https://papermc.io/api/v1/paper/**1.14.4**/137/download

**Comment by zachbr** [comment]
Clear your cache, refresh your browser, etc.
Site has been updated for some time now, it is completely bypassing all edge caching, there is nothing more to be done on our end.

**Comment by eccentricdevotion** [comment]
Thanks, should have thought of that myself...
