### ISSUE TITLE
Soul sand underwater wrong

### ISSUE THREAD

**Issue by myk3sr** [PaperMC/papermc.io#45]
Soul sand uunderwater should push up air and make player float to the top, it pulls u down the opposite, which is what magma block should do. It's very strange because it does push npc squids up even out of the water which is  correct, but players get sucked down. Boats sink also.

Strange, figured I'd mention

**Comment by kashike** [comment]
You have opened this issue on the wrong repository - you most likely want the [Paper](https://github.com/PaperMC/Paper) repository.
