### ISSUE TITLE
Download button arrows don't show on Firefox

### ISSUE THREAD

**Issue by zachbr** [PaperMC/papermc.io#6]
It should look like this 
<img width="1258" alt="screen shot 2018-10-23 at 5 51 43 pm" src="https://user-images.githubusercontent.com/1254957/47393038-6a5e7000-d6ec-11e8-86b1-a29fe87ac90b.png">

But instead it looks like this

<img width="1360" alt="screen shot 2018-10-23 at 5 51 16 pm" src="https://user-images.githubusercontent.com/1254957/47393050-72b6ab00-d6ec-11e8-9bb8-57073a5d2aa2.png">

Notice the missing arrows in the download buttons.

**Comment by aikar** [comment]
could use the cloud icon maybe? I kinda think that one pairs better anyways

**Comment by zachbr** [comment]
Cloud icon would just come from the same source and be about the same size. We should probably figure out *why* the current icon isn't showing.

Though I'd agree the cloud icon is nice.

**Comment by DemonWav** [comment]
Wow literally unusable.

**Comment by zachbr** [comment]
@MiniDigger looks good across safari and chrome as well. Thanks
