### ISSUE TITLE
Jenkins Automation Server

### ISSUE THREAD

**Issue by EclipseKnight** [PaperMC/papermc.io#62]
I have a script that had simply pulled the latest successful build from the jenkins automation server used with the project. Acessible via the "more" button on the site. 

It seems this has been removed and the only way to grab the latest build I can find now is via the site's download page. Only issue is the original url [https://papermc.io/ci/job/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar](https://papermc.io/ci/job/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar) would point to the generically named lastest build jar. 

Meanwhile, the site's url is dynamically changing based on the number of the release. Would it be possible to implement a static URL pointing to the last build for ease of updating. It's a hassle having to manually download the latest build when I could just run a script.

**Comment by aurorasmiles** [comment]
The old API and jenkins have been deprecated, use the new API instead: https://papermc.io/api/docs/

> Would it be possible to implement a static URL pointing to the last build for ease of updating. 
No, we have decided against that for various reasons.
