### ISSUE TITLE
check if cookie consent did load

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/papermc.io#69]
I hate cookie popups, so I got a plugin that removes them.

this breaks the website

```
Uncaught ReferenceError: cookieconsent is not defined
    at HTMLDocument.<anonymous> (script.js?v=09c68fa2a70045c3:34)
```

```
 cookieconsent.initialise({
```

we just need to null check cookieconsent here.

this breaks all dropdowns, since those get initialized after cookie consent.

https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja

**Comment by zachbr** [comment]
Nice

**Comment by MiniDigger** [comment]
![image](https://user-images.githubusercontent.com/2185527/108987701-dfaf2680-7693-11eb-9daa-11f8439875a5.png)
