### ISSUE TITLE
Somehow advertise Maven coordinates under "An expanded API"

### ISSUE THREAD

**Issue by Trigary** [PaperMC/papermc.io#71]
The [homepage](https://papermc.io/) contains a section titled "An expanded API". It has a link to the [JavaDocs](https://papermc.io/javadocs) page. But I would also expect to somehow be able to find the Maven coordinates for this "expanded API".

Possible solutions I see:
 - Stating in the "expanded API" section that the Maven coordinates can be found on the GitHub page
 - Stating in the [JavaDocs](https://papermc.io/javadocs) page that the Maven coordinates can be found on the respective GitHub pages (Plural since the JavaDocs page also contains a link to Waterfall.)
 - Specifying the Maven coordinates in the "expanded API" section
 - Specifying the Maven coordinates in the [JavaDocs](https://papermc.io/javadocs) page (For both Paper and Waterfall since both of them are listed in the JavaDocs page.)

**Comment by simpleauthority** [comment]
I vote this one:
> Specifying the Maven coordinates in the "expanded API" section

**Comment by kashike** [comment]
#72
