### ISSUE TITLE
highlight.js css is not loading on the api coordinates page

### ISSUE THREAD

**Issue by simpleauthority** [PaperMC/papermc.io#74]
Visit this page [https://papermc.io/using-the-api#maven](https://papermc.io/using-the-api) and observe that the highlight.js module is working fine but that the CSS is not loaded. 

Looking at the page source shows `<link type="text/css" rel="stylesheet" href="" media="screen, projection">` for the line where it should be including the CSS. Did something go wrong in the build or perhaps did I mess up the process for including new CSS in the last PR (#72)?

**Comment by MiniDigger** [comment]
I bet it doesnt like you have it the scss extension
