### ISSUE TITLE
Is THAT normal?

### ISSUE THREAD

**Issue by RozeFound** [PaperMC/papermc.io#87]
![image](https://user-images.githubusercontent.com/68745888/121229330-fdf20880-c8b7-11eb-9077-82cc8eef16d6.png)

**Comment by Machine-Maker** [comment]
Looks fine to me... do a hard refresh maybe? to clear browser cache, or maybe some extension you have is blocking some resource from being loaded.

**Comment by Proximyst** [comment]
Clear cache and ensure you don't use an ad-blocker; the resources are available and work fine.

**Comment by RozeFound** [comment]
Hard refresh and clearing cache didn't work, ad-blocker off on this site. Did you guys tried to open your site in Edge?

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/121230358-0ed65600-c887-11eb-919a-131466021caf.png)

**Comment by Malfrador** [comment]
Works fine in Edge (Version 91.0.864.41, no Addons) for me.

**Comment by RozeFound** [comment]
Can it be a country dependent?

**Comment by electronicboy** [comment]
resources are distributed through cloudflare

**Comment by sulu5890** [comment]
Open your browsers debugger and ensure materialicons are loading, if they aren't it should tell you why.

**Comment by RozeFound** [comment]
Only font isn't loaded with code 500. And analytics.js for some reason

**Comment by RozeFound** [comment]
Oh, I found the solution. Thanks! It was ad-blocker with anti-thirdparty fonts (I don't know why I've installed this), I disabled this filter and now all works fine. And for some reason ad-blocker not completly stop filter the site.
