### ISSUE TITLE
Spanish translation of the website.

### ISSUE THREAD

**Issue by pangolp** [PaperMC/papermc.io#98]
Hello, good evening, would it be possible to add a folder /es/ inside the source and make translations of the files to spanish? I ask, because if it is possible, I would like to collaborate with such translations or at least try to do it. Thanks for your answer.

**Comment by MiniDigger** [comment]
hey, thanks for your interest, but with the current setup thats not really possible.

I wanna redo the website long term and look at stuff like that, but for now that would be too much work to maintain.

**Comment by pangolp** [comment]
What web technologies do you use the most?
I have worked with
- Python / Django
- Node
- Vue
- Some php

I recently created a blog, with Pelican, which is a Python library, where you can use Markdown, but you could also use this: https://github.com/Drassil/git-wiki-theme

**Comment by pangolp** [comment]
That project I named you at the end, is the one used by the AzerothCore community, for its wiki, and recently, Spanish support was added. We are going to start translating the files, which are markdown files.
https://www.azerothcore.org/wiki/home
