### ISSUE TITLE
Small typos i think

### ISSUE THREAD

**Issue by Chris6ix** [PaperMC/papermc.io#99]
Hey guys, just wanted to tell you that i think a found some small typos in your downloads page...
My english isnt perfect but shouldnt it be "they may still have issues..." or "there may still be issues..."? (Pr #100) 
![image](https://user-images.githubusercontent.com/65610536/124006630-c9ff9400-d9da-11eb-852b-53b66587b476.png)

And the Update #50 says "paerweight" instead of "paperweight"
![image](https://user-images.githubusercontent.com/65610536/124007160-632eaa80-d9db-11eb-9db4-66e199b2f90a.png)

Kind Regards,
Chris6ix

**Comment by TwoLeggedCat** [comment]
Since I see you forking the repo, you're right about the first part, but that message is going away after a while anyway. Whoever wrote it was probably thinking "there may still be issues and bugs." The second one is a commit message which can't really be changed and will just have to stay a typo.

**Comment by Chris6ix** [comment]
Yeah i made a pr to fix the first typo
Okay the 2nd one then just stays ¯\_(ツ)_/¯

Thx btw for your fast answer :)

**Comment by sulu5890** [comment]
ad2ef658e548ea8f608c935a92cffe0bd7a73153
